### PR TITLE
Added bunch of extra functionality

### LINKED ISSUE #3: Inconsistent Notification screen preview
In the Notification tab, the image preview shows the old style, before the changes in this fork:

image

### PR DESCRIPTION
**Pull request by kuukunen**
Hi, I saw your fork of the project and started using it, but it was still lacking some features I wanted so I added them. I'll also send PR up to Grabacr07, but he seems to not be super active on it.

- Rename desktops
- Switch to specific desktop
- Move window to specific desktop
- Switch to previous desktop
- Reset to default settings

Also bunch of tweaks.

### CODE REVIEW

**Comment by ViRb3** [comment]
Hey there! I don't know how I have missed this, but I just saw it by pure accident. I will test, review, and hopefully merge ASAP. Thanks so much for the PR!

**Comment by ViRb3** [comment]
Here's a couple of issues I noticed during my initial test:

- Rename window doesn't take focus. This means that the user has to click on the rename window in order to type in it, which I think is counter-productive and counter-intuitive.

- Text not replaced in shortuct title:
image

If you could kindly fix these bugs I can merge straight away. If you are busy I can do it as well tomorrow.

**Comment by kuukunen** [comment]
Btw, there's a bit more info about possible issues and stuff on https://github.com/Grabacr07/SylphyHorn/pull/46

Yea I noticed the text issue... but then promptly forgot about it. I've no idea how it was ever supposed to work. As a sidenote, it took me like an hour to figure out how to do properly... As mentioned in the above link, I'm not a C# developer and had no idea about WPF before modifying this.

And yea, the D1 etc comes straight from... I don't know where, but it's automatic.

As for the rename window focus thing, I totally agree, it should grab the focus. I tried to fix it multiple times until I got something that Works For Me™. It could be some sort of stupid race condition. However, since it works for me, I don't know how to fix it properly... I've no idea what would be the correct way of doing it either (see above), currently I just put it in the Activated event handler in RenameWindow.xaml.cs:79, if you want to take a look.

**Comment by ViRb3** [comment]
I will polish things up and hopefully merge this PR by the end of today :)

**Comment by ViRb3** [comment]
Closes #3

**Comment by ViRb3** [comment]
I made a few small changes, but for your first C# WPF work I am amazed by the quality of this PR. Thank you so much on behalf of everyone who uses this tool!

**Comment by ViRb3** [comment]
Also good news @kuukunen, I managed to reliably fix rename window focus in 3c851130291c7671d3313725b55834281e311298.

**Comment by kuukunen** [comment]
Ah ok nice. I'm using it a lot right now myself, so might get annoyed by some more things in the future. We'll see.

**Pull request merged**
